[build-system]
requires = [
    "setuptools", 
    "wheel", 
    "numpy", 
    "meson>=0.64.0",        #build-time only
    "ninja",                #build-time only
    "meson-python>=0.13.0"  #build-time only
]
build-backend = "mesonpy"

[project]
name = "wannier-tools"
version = "2.7.1"
description = "WannierTools: An open-source software package for novel topological materials"
authors = [
    { name = "QuanSheng Wu", email = "wuquansheng@gmail.com" },
    { name = "ShengNan Zhang" },
    { name = "Hai-Feng Song" },
    { name = "Matthias Troyer" },
    { name = "Alexey A. Soluyanov" },
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Fortran",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.scripts]
wt-py = "wannier_tools.cli:main"
wt-check-deps = "wannier_tools.check_deps:main"

[project.urls]
Homepage = "https://www.wanniertools.com/"
"Bug Tracker" = "https://github.com/quanshengwu/wannier_tools/issues"

[tool.meson-python.args]
install = ["--tags=python-runtime,extension,devel"]

# cibuildwheel配置
[tool.cibuildwheel]
# 构建哪些版本
build = ["cp39-*"]
# 跳过哪些版本
skip = ["pp*", "*musllinux*"]

# 测试设置
test-command = [
    "python -c \"import wannier_tools; print('Import successful')\"",
    "python -c \"import wannier_tools; print('Version:', wannier_tools.__version__)\""
]
test-requires = ["pytest"]

# 环境变量在各平台特定配置中设置

# Linux特定配置
[tool.cibuildwheel.linux]
archs = ["x86_64"]
manylinux-x86_64-image = "wanniertools-builder-nompi"
environment = { FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", WANNIERTOOLS_RUNTIME_MPI_ONLY = "true" }
before-build = [
    "echo 'Building Linux wheels with runtime MPI detection'",
    "echo 'Available Python versions:'",
    "ls /opt/python/"
]

# macOS特定配置 - 支持三种架构
[tool.cibuildwheel.macos] 
archs = ["x86_64", "arm64", "universal2"]
# 设置基础环境变量，架构特定配置在before-build中处理
environment = { FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", MACOSX_DEPLOYMENT_TARGET = "14.0", WANNIERTOOLS_RUNTIME_MPI_ONLY = "true" }
before-build = [
    "echo 'Building macOS wheels with runtime MPI detection'",
    "echo \"Target architecture: $CIBW_ARCHS_MACOS\"",
    "echo \"Build machine: `uname -m`\"",
    
    # 安装依赖 - gcc提供gfortran，但C/C++用Clang
    "brew install gcc openblas arpack",
    
    # 架构特定配置 - 修复变量展开
    "if [[ \"$CIBW_ARCHS_MACOS\" == \"arm64\" ]]; then export BREW_PREFIX=/opt/homebrew && export ARCH_FLAGS=\"-arch arm64\" && echo 'Configuring for Apple Silicon (ARM64)'; elif [[ \"$CIBW_ARCHS_MACOS\" == \"universal2\" ]]; then export BREW_PREFIX=/opt/homebrew && export ARCH_FLAGS=\"-arch arm64 -arch x86_64\" && echo 'Configuring for Universal Binary (ARM64 + x86_64)'; else export BREW_PREFIX=/usr/local && export ARCH_FLAGS=\"-arch x86_64\" && echo 'Configuring for Intel (x86_64)'; fi",
    "echo \"Using Homebrew prefix: $BREW_PREFIX\"",
    "echo \"Architecture flags: $ARCH_FLAGS\"",
    
    # 设置编译器 - Clang for C/C++, gfortran for Fortran
    "export CC=clang",
    "export CXX=clang++", 
    "export FC=$BREW_PREFIX/bin/gfortran",
    
    # 将架构和路径选项放入FLAGS而不是编译器变量
    "export CFLAGS=\"$ARCH_FLAGS\"",
    "export CXXFLAGS=\"$ARCH_FLAGS\"",
    "export FFLAGS=\"$ARCH_FLAGS -fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch\"",
    "export LDFLAGS=\"$ARCH_FLAGS -L$BREW_PREFIX/lib -Wl,-rpath,$BREW_PREFIX/lib\"",
    "export CPPFLAGS=\"-I$BREW_PREFIX/include\"",
    "export PKG_CONFIG_PATH=\"$BREW_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}\"",
    
    # 强制Meson使用我们指定的编译器，避免自动检测gcc
    "export MESON_CC=clang",
    "export MESON_CXX=clang++",
    
    # 创建临时gcc软链接作为备用方案（指向clang）
    "mkdir -p /tmp/wanniertools_build_bin",
    "ln -sf $(which clang) /tmp/wanniertools_build_bin/gcc",
    "ln -sf $(which clang++) /tmp/wanniertools_build_bin/g++", 
    "ln -sf $(which ar) /tmp/wanniertools_build_bin/gcc-ar",
    "export PATH=\"/tmp/wanniertools_build_bin:$PATH\"",
    "echo \"Temporary build PATH: $PATH\"",
    
    # 验证编译器设置
    "echo 'Compiler configuration:'",
    "echo \"CC=$CC ($(which $CC))\"",
    "echo \"CXX=$CXX ($(which $CXX))\"", 
    "echo \"FC=$FC\"",
    "echo \"CFLAGS=$CFLAGS\"",
    "echo \"FFLAGS=$FFLAGS\"",
    "$CC --version | head -1",
    "test -f $FC && $FC --version | head -1 || echo 'WARNING: gfortran not found'",
    "echo 'Available libraries:'",
    "ls -la $BREW_PREFIX/lib/ | grep -E '(blas|arpack|gfortran)' || echo 'Libraries not found'"
]

# Windows特定配置
[tool.cibuildwheel.windows]
archs = ["AMD64"]
environment = { FC = "gfortran", CC = "gcc", CXX = "g++", FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", OPENBLAS_NUM_THREADS = "1", OMP_NUM_THREADS = "1" }
before-build = [
    "echo Installing Windows wheels with hybrid gfortran+MS-MPI compatibility",
    "pip install delvewheel",
    "echo Installing MSYS2 gfortran-compatible libraries...",
    "C:\\msys64\\usr\\bin\\pacman.exe -S --noconfirm mingw-w64-x86_64-openblas",
    "echo Installing MSYS2 gfortran-compatible MS-MPI development libraries...",
    "C:\\msys64\\usr\\bin\\pacman.exe -S --noconfirm mingw-w64-x86_64-msmpi",
    "echo Installing official MS-MPI Runtime for mpiexec.exe...",
    "powershell -Command \"Invoke-WebRequest -Uri 'https://download.microsoft.com/download/a/5/2/a5207ca5-1203-491a-8fb8-906fd68ae623/msmpisetup.exe' -OutFile 'msmpisetup.exe'\"",
    "powershell -Command \"Start-Process -FilePath '.\\msmpisetup.exe' -ArgumentList '-unattend' -Wait -NoNewWindow\"",
    "echo Configuring hybrid environment: MSYS2 PATH + MS-MPI Runtime...",
    "set PATH=C:\\msys64\\mingw64\\bin;C:\\Program Files\\Microsoft MPI\\Bin;%PATH%",
    "echo Verifying gfortran-compatible MPI headers and libraries...",
    "dir C:\\msys64\\mingw64\\include\\mpi.h",
    "dir C:\\msys64\\mingw64\\lib\\libmsmpi.dll.a",
    "echo Verifying MS-MPI runtime (mpiexec.exe)...",
    "powershell -Command \"& \\\"$env:ProgramFiles\\Microsoft MPI\\Bin\\mpiexec.exe\\\" -help | Select-Object -First 5\"",
    "echo [OK] Hybrid compatibility configured: gfortran libs + MS-MPI runtime"
]
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel} --add-path C:\\msys64\\mingw64\\bin" 