[build-system]
requires = [
    "setuptools", 
    "wheel", 
    "numpy", 
    "meson>=0.64.0",        #build-time only
    "ninja",                #build-time only
    "meson-python>=0.13.0"  #build-time only
]
build-backend = "mesonpy"

[project]
name = "wannier-tools"
version = "2.7.1"
description = "WannierTools: An open-source software package for novel topological materials"
authors = [
    { name = "QuanSheng Wu", email = "wuquansheng@gmail.com" },
    { name = "ShengNan Zhang" },
    { name = "Hai-Feng Song" },
    { name = "Matthias Troyer" },
    { name = "Alexey A. Soluyanov" },
]
license = { text = "GPL-3.0-or-later" }
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20.0",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: GNU General Public License v3 or later (GPLv3+)",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Fortran",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.scripts]
wt-py = "wannier_tools.cli:main"
wt-check-deps = "wannier_tools.check_deps:main"

[project.urls]
Homepage = "https://www.wanniertools.com/"
"Bug Tracker" = "https://github.com/quanshengwu/wannier_tools/issues"

[tool.meson-python.args]
install = ["--tags=python-runtime,extension,devel"]

# cibuildwheel配置
[tool.cibuildwheel]
# 构建哪些版本
build = ["cp39-*"]
# 跳过哪些版本
skip = ["pp*", "*musllinux*"]

# 测试设置
test-command = [
    "python -c \"import wannier_tools; print('Import successful')\"",
    "python -c \"import wannier_tools; print('Version:', wannier_tools.__version__)\""
]
test-requires = ["pytest"]

# 环境变量在各平台特定配置中设置

# Linux特定配置
[tool.cibuildwheel.linux]
archs = ["x86_64"]
manylinux-x86_64-image = "wanniertools-builder-nompi"
environment = { FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", WANNIERTOOLS_RUNTIME_MPI_ONLY = "true" }
before-build = [
    "echo 'Building Linux wheels with runtime MPI detection'",
    "echo 'Available Python versions:'",
    "ls /opt/python/"
]

# macOS特定配置
[tool.cibuildwheel.macos]
archs = ["x86_64", "arm64"]
# 通用环境变量，路径将在before-build中动态设置
environment = { CC = "clang", CXX = "clang++", FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", MACOSX_DEPLOYMENT_TARGET = "14.0", WANNIERTOOLS_RUNTIME_MPI_ONLY = "true" }
before-build = [
    "echo 'Building macOS wheels with runtime MPI detection'",
    "echo 'Target architecture: ${CIBW_ARCHS_MACOS:-unknown}'",
    "echo 'Build machine: $(uname -m)'",
    # 检测Homebrew路径并写入环境文件
    "if [ -d /opt/homebrew ]; then BREW_PREFIX=/opt/homebrew; else BREW_PREFIX=/usr/local; fi",
    "echo \"Using Homebrew prefix: $BREW_PREFIX\"",
    # 创建环境设置文件
    "echo \"export FC=$BREW_PREFIX/bin/gfortran\" > /tmp/macos_build_env.sh",
    "echo \"export PKG_CONFIG_PATH=$BREW_PREFIX/lib/pkgconfig:${PKG_CONFIG_PATH:-}\" >> /tmp/macos_build_env.sh",
    "echo \"export LDFLAGS='-L$BREW_PREFIX/lib -Wl,-rpath,$BREW_PREFIX/lib ${LDFLAGS:-}'\" >> /tmp/macos_build_env.sh",
    "echo \"export CPPFLAGS='-I$BREW_PREFIX/include ${CPPFLAGS:-}'\" >> /tmp/macos_build_env.sh",
    # 应用环境设置
    "source /tmp/macos_build_env.sh",
    # 安装编译器
    "brew install gcc",
    "echo 'Compiler information:'",
    "which clang && clang --version | head -n1",
    "which gfortran && gfortran --version | head -n1", 
    "echo 'Build environment:'",
    "cat /tmp/macos_build_env.sh",
    "echo 'Available libraries:'",
    "ls -la $BREW_PREFIX/lib/ | grep -E '(blas|arpack)' || echo 'No BLAS/ARPACK found'"
]

# Windows特定配置
[tool.cibuildwheel.windows]
archs = ["AMD64"]
environment = { FC = "gfortran", CC = "gcc", CXX = "g++", FFLAGS = "-fallow-invalid-boz -fbackslash -ffree-line-length-none -fallow-argument-mismatch", WANNIERTOOLS_RUNTIME_MPI_ONLY = "true" }
before-build = [
    "echo Building Windows wheels",
    "pip install delvewheel",
    "C:\\msys64\\usr\\bin\\pacman.exe -S --noconfirm mingw-w64-x86_64-openblas",
    "set PATH=C:\\msys64\\mingw64\\bin;%PATH%",
    "gcc --version",
    "gfortran --version"
]
repair-wheel-command = "delvewheel repair -w {dest_dir} {wheel}" 